<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CloudInventory.Application\CloudInventory.Application.csproj" />
    <ProjectReference Include="..\CloudInventory.Domain\CloudInventory.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="4.0.102.7" />
    <PackageReference Include="AWSSDK.SecurityToken" Version="4.0.101" />
    <PackageReference Include="AWSSDK.SSO" Version="4.0.100.16" />
    <PackageReference Include="AWSSDK.SSOOIDC" Version="4.0.100.15" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
